name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    services:
      mysql:
        image: mysql:5.7
        env:
          DATABASE = holcemlk_banker_dataentry
          DATABASE_HOST = 209.133.220.90
          DATABASE_USER = holcemlk_user
          DATABASE_PASSWORD = PRB1WgD?41zW
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host=localhost --user=root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Build the Application (If Applicable)
      run: npm run build --if-present

    - name: Wait for MySQL to be Ready
      run: sleep 10s

    - name: Run Application
      run: npm start &  # Run in the background to prevent workflow hanging

    - name: Verify Server is Running
      run: curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:3000 || exit 1
